<?php
/**
 * Configuration file generated by ZFTool
 * 
 * @see https://github.com/zendframework/ZFTool
 * 
 * Informs the ModuleManager all the modules in the application it is to 
 * manage
 */
return array(
    'modules' => array(
        'Application',
        'Dips'
    ),
    'module_listener_options' => array(
        'config_glob_paths'    => array(
            'config/autoload/{,*.}{global,local}.php',
            //'config/autoload/{,*.}{global,local}.json',
        ),
        'module_paths' => array(
            './module',
            './vendor',
        ),
      )
    );
